export const ExamCategories = [
  {
    id: "biochemistry",
    name: "Bioquímica",
    exams: [
      { id: "arterial-blood-gas", name: "Gasometria Arterial", isSelected: false },
      { id: "venous-blood-gas", name: "Gasometria Venosa", isSelected: false },
      { id: "glucose", name: "Glicose", isSelected: false },
      { id: "urea", name: "Ureia", isSelected: false },
      { id: "creatinine", name: "Creatinina", isSelected: false },
      { id: "uric-acid", name: "Ácido Úrico", isSelected: false },
      { id: "sodium", name: "Sódio", isSelected: false },
      { id: "potassium", name: "Potássio", isSelected: false },
      { id: "calcium", name: "Cálcio", isSelected: false },
      { id: "ionized-calcium", name: "Cálcio Ionizado", isSelected: false },
      { id: "phosphorus", name: "Fósforo", isSelected: false },
      { id: "magnesium", name: "Magnésio", isSelected: false },
      { id: "chlorine", name: "Cloro", isSelected: false },
      { id: "iron", name: "Ferro", isSelected: false },
      { id: "ferritin", name: "Ferritina", isSelected: false },
      { id: "triglycerides", name: "Triglicerídeos", isSelected: false },
      { id: "cholesterol-total", name: "Colesterol Total", isSelected: false },
      { id: "hdl", name: "HDL", isSelected: false },
      { id: "ldl", name: "LDL", isSelected: false },
      { id: "vldl", name: "VLDL", isSelected: false },
      { id: "total-proteins", name: "Proteínas Totais e Frações", isSelected: false },
      { id: "albumin", name: "Albumina", isSelected: false },
      { id: "bilirubin", name: "Bilirrubina (Total e Frações)", isSelected: false },
      { id: "alkaline-phosphatase", name: "Fosfatase Alcalina", isSelected: false },
      { id: "acid-phosphatase", name: "Fosfatase Ácida", isSelected: false },
      { id: "amylase", name: "Amilase", isSelected: false },
      { id: "ldh", name: "Desidrogenase Láctica (LDH)", isSelected: false },
      { id: "ast", name: "AST (TGO)", isSelected: false },
      { id: "alt", name: "ALT (TGP)", isSelected: false },
      { id: "gamma-gt", name: "Gama-GT", isSelected: false },
      { id: "ck-total", name: "CK Total", isSelected: false },
      { id: "ck-mb", name: "CK-MB", isSelected: false },
      { id: "myoglobin", name: "Mioglobina", isSelected: false },
      { id: "troponin", name: "Troponina", isSelected: false },
      { id: "osmolarity", name: "Osmolaridade", isSelected: false },
      { id: "protein-electrophoresis", name: "Eletroforese de Proteínas", isSelected: false },
      { id: "hba1c", name: "Hemoglobina Glicada (HbA1c)", isSelected: false },
      { id: "vitamin-b12", name: "Vitamina B12", isSelected: false },
      { id: "vitamin-d3", name: "Vitamina D3", isSelected: false },
      { id: "zinc", name: "Zinco", isSelected: false },
      { id: "folate", name: "Ácido Fólico", isSelected: false },
      { id: "lactic-acid", name: "Ácido Lático", isSelected: false },
      { id: "fructosamine", name: "Frutosamina", isSelected: false },
      { id: "insulin", name: "Insulina", isSelected: false },
      { id: "peptide-c", name: "Peptídeo C", isSelected: false },
      { id: "ace", name: "Enzima Conversora de Angiotensina (ECA)", isSelected: false },
    ],
  },
  {
    id: "hematology",
    name: "Hematologia",
    exams: [
      { id: "cbc", name: "Hemograma Completo", isSelected: false },
      { id: "esr", name: "ESR/VHS (Velocidade de Hemossedimentação)", isSelected: false },
      { id: "white-cell-count", name: "Leucograma", isSelected: false },
      { id: "red-blood-cells", name: "Eritograma", isSelected: false },
      { id: "platelets", name: "Plaquetas", isSelected: false },
      { id: "hemoglobin", name: "Hemoglobina (Hb)", isSelected: false },
      { id: "hematocrit", name: "Hematócrito (Ht)", isSelected: false },
      { id: "reticulocytes", name: "Reticulócitos", isSelected: false },
      { id: "coombs-test", name: "Teste de Coombs (Direto e Indireto)", isSelected: false },
      { id: "peripheral-blood-smear", name: "Sangue Periférico", isSelected: false },
      { id: "hemoglobin-electrophoresis", name: "Eletroforese de Hemoglobina", isSelected: false },
      { id: "fibrinogen", name: "Fibrinogênio", isSelected: false },
      { id: "bleeding-time", name: "Tempo de Sangramento (TS)", isSelected: false },
      { id: "clotting-time", name: "Tempo de Coagulação (TC)", isSelected: false },
      { id: "prothrombin-time", name: "Tempo de Protrombina (TP + INR)", isSelected: false },
      { id: "aptt", name: "TTPa (Tempo de Tromboplastina Parcial Ativada)", isSelected: false },
      { id: "thrombin-time", name: "Tempo de Trombina (TT)", isSelected: false },
      { id: "antithrombin-iii", name: "Antitrombina III", isSelected: false },
      { id: "platelet-aggregation", name: "Agregação Plaquetária", isSelected: false },
      { id: "activated-clotting-time", name: "Tempo de Coagulação Ativado (TCA)", isSelected: false },
      { id: "d-dimer", name: "D-Dímero", isSelected: false },
      { id: "g6pd", name: "Glicose-6-Fosfato Desidrogenase (G6PD)", isSelected: false },
      { id: "blood-grouping", name: "Grupo Sanguíneo", isSelected: false },
    ],
  },
  {
    id: "hormones",
    name: "Hormônios",
    exams: [
      { id: "tsh", name: "TSH (Ultrasensível)", isSelected: false },
      { id: "t3", name: "T3 Total / Livre", isSelected: false },
      { id: "t4", name: "T4 Total / Livre", isSelected: false },
      { id: "lh", name: "LH", isSelected: false },
      { id: "fsh", name: "FSH", isSelected: false },
      { id: "testosterone", name: "Testosterona / Testosterona Livre", isSelected: false },
      { id: "estradiol", name: "Estradiol", isSelected: false },
      { id: "progesterone", name: "Progesterona", isSelected: false },
      { id: "prolactin", name: "Prolactina", isSelected: false },
      { id: "acth", name: "ACTH", isSelected: false },
      { id: "cortisol", name: "Cortisol", isSelected: false },
      { id: "insulin", name: "Insulina", isSelected: false },
      { id: "bhcg", name: "BHCG (Qualitativo & Quantitativo)", isSelected: false },
      { id: "aldosterone", name: "Aldosterona", isSelected: false },
      { id: "angiotensin-ii", name: "Angiotensina II", isSelected: false },
      { id: "erythropoietin", name: "Eritropoetina", isSelected: false },
    ],
  },
  {
    id: "tumor-markers",
    name: "Marcadores Tumorais",
    exams: [
      { id: "psa", name: "PSA (Total e Livre)", isSelected: false },
      { id: "afp", name: "Alfa-fetoproteína (AFP)", isSelected: false },
      { id: "ca-125", name: "CA 125", isSelected: false },
      { id: "ca-19-9", name: "CA 19-9", isSelected: false },
      { id: "ca-15-3", name: "CA 15-3", isSelected: false },
      { id: "ca-72-4", name: "CA 72-4", isSelected: false },
      { id: "cyfra-21", name: "CYFRA 21", isSelected: false },
      { id: "cea", name: "CEA", isSelected: false },
      { id: "beta-hcg", name: "Beta-HCG (Quantitativo)", isSelected: false },
    ],
  },
  {
    id: "immunology-infectious",
    name: "Imunologia e Doenças Infecciosas",
    exams: [
      { id: "aso", name: "Anti-Estrptolisina O (ASO)", isSelected: false },
      { id: "pcr", name: "Proteína C Reativa (PCR)", isSelected: false },
      { id: "rf", name: "Fator Reumatoide (FR)", isSelected: false },
      { id: "alpha1-glycoprotein", name: "Glicoproteína Ácida Alfa-1", isSelected: false },
      { id: "c3-c4", name: "C3 / C4", isSelected: false },
      { id: "immunoglobulins", name: "Imunoglobulinas: IgG, IgM, IgA, IgE Total", isSelected: false },
      { id: "fan", name: "Anticorpos Antinucleares (FAN)", isSelected: false },
      { id: "anti-thyroglobulin", name: "Anti-tireoglobulina", isSelected: false },
      { id: "anti-tpo", name: "Anti-TPO", isSelected: false },
      { id: "hbsag", name: "HBsAg", isSelected: false },
      { id: "anti-hbs", name: "Anti-HBs", isSelected: false },
      { id: "anti-hbc", name: "Anti-HBc Total / IgM", isSelected: false },
      { id: "hbeag", name: "HBeAg", isSelected: false },
      { id: "anti-hbe", name: "Anti-HBe", isSelected: false },
      { id: "anti-hav", name: "Anti-HAV IgG / IgM", isSelected: false },
      { id: "anti-hcv", name: "Anti-HCV", isSelected: false },
      { id: "cd4-cd8", name: "Subpopulações Linfocitárias: CD4+, CD8+", isSelected: false },
      { id: "cmv", name: "Citomegalovírus IgG / IgM", isSelected: false },
      { id: "vdrl", name: "VDRL / RPR", isSelected: false },
      { id: "tpha", name: "TPHA", isSelected: false },
      { id: "anti-hiv", name: "Anti-HIV", isSelected: false },
      { id: "western-blot", name: "Western Blot (HIV)", isSelected: false },
      { id: "paul-bunnell", name: "Paul Bunnell", isSelected: false },
      { id: "rubella", name: "Rubéola IgG / IgM", isSelected: false },
      { id: "toxoplasma", name: "Toxoplasmose IgG / IgM", isSelected: false },
      { id: "ebv", name: "Vírus Epstein-Barr", isSelected: false },
      { id: "hsv", name: "Herpes Simples I e II (IgG / IgM)", isSelected: false },
      { id: "h-pylori", name: "H. Pylori IgG / IgM", isSelected: false },
      { id: "anca", name: "ANCA", isSelected: false },
      { id: "rpr", name: "RPR", isSelected: false },
      { id: "hla-b27", name: "HLA-B27", isSelected: false },
      { id: "chlamydia", name: "Chlamydia (IgA, IgG, IgM)", isSelected: false },
      { id: "schistosoma", name: "Schistosoma", isSelected: false },
      {
        id: "allergy-testing",
        name: "Testes de Alergia: ECP, IgE Total, Phadiatop, Phadiatop Pediátrico, Tryptase",
        isSelected: false,
      },
    ],
  },
  {
    id: "microbiology",
    name: "Microbiologia",
    exams: [
      { id: "culture-blood", name: "Cultura: Sangue", isSelected: false },
      { id: "culture-urine", name: "Cultura: Urina", isSelected: false },
      { id: "culture-feces", name: "Cultura: Fezes", isSelected: false },
      { id: "culture-sputum", name: "Cultura: Escarro", isSelected: false },
      { id: "culture-nasal", name: "Cultura: Nasal", isSelected: false },
      { id: "culture-throat", name: "Cultura: Garganta", isSelected: false },
      { id: "culture-vaginal", name: "Cultura: Vaginal", isSelected: false },
      { id: "culture-semen", name: "Cultura: Sêmen", isSelected: false },
      { id: "exudate-swabs", name: "Swab para Exsudato", isSelected: false },
      { id: "culture-mycobacteria", name: "Cultura para Micobactérias (BK)", isSelected: false },
      { id: "culture-fungi", name: "Cultura para Fungos", isSelected: false },
      { id: "culture-urogenital", name: "Cultura Urogenital", isSelected: false },
      { id: "culture-nasopharyngeal", name: "Cultura Nasofaríngea", isSelected: false },
      { id: "culture-urethral", name: "Cultura Uretral", isSelected: false },
      { id: "bacilloscopy", name: "Baciloscopia", isSelected: false },
      { id: "gram-stain", name: "Coloração de Gram", isSelected: false },
      { id: "rickettsia", name: "Rickettsia", isSelected: false },
      { id: "plasmodium", name: "Plasmodium (Malária)", isSelected: false },
      { id: "microfilaria", name: "Microfilárias", isSelected: false },
      { id: "antigen-detection", name: "Detecção de Antígenos: Pneumococo / Legionella", isSelected: false },
      { id: "genexpert", name: "GeneXpert (TB)", isSelected: false },
      { id: "paul-bunnell", name: "Paul Bunnell", isSelected: false },
    ],
  },
  {
    id: "urianalysis",
    name: "Uroanálise",
    exams: [
      { id: "urinalysis", name: "EAS (Urina Rotina)", isSelected: false },
      { id: "protein-24h", name: "Proteína 24h", isSelected: false },
      { id: "calcium-24h", name: "Cálcio 24h", isSelected: false },
      { id: "creatinine-clearance", name: "Depuração de Creatinina", isSelected: false },
      { id: "urinary-albumin", name: "Albumina Urinária", isSelected: false },
      { id: "protein-urine-24h", name: "Proteína na Urina 24h", isSelected: false },
      { id: "acidified-urine-test", name: "Teste de Acidificação da Urina (24h)", isSelected: false },
    ],
  },
]
