import { PlanType, PlanTypeForPatient } from "@/types"

export const PlanListForProvider = [
  {
    type: PlanType.Business,
    titleKey: "provider.business.title",
    priceKey: "provider.business.price",
    ctaKey: "provider.business.cta",
    featuresKeys: [
      "provider.business.features.0",
      "provider.business.features.1",
      "provider.business.features.2",
      "provider.business.features.3",
    ],
  },
  {
    type: PlanType.BusinessPlus,
    titleKey: "provider.businessPlus.title",
    featured: "provider.businessPlus.featured",
    priceKey: "provider.businessPlus.price",
    featuresKeys: [
      "provider.businessPlus.features.0",
      "provider.businessPlus.features.1",
      "provider.businessPlus.features.2",
      "provider.businessPlus.features.3",
      "provider.businessPlus.features.4",
      "provider.businessPlus.features.5",
      "provider.businessPlus.features.6",
    ],
    ctaKey: "provider.businessPlus.cta",
    currency: "provider.businessPlus.currency",
    period: "provider.businessPlus.period",
  },
  {
    type: PlanType.Company,
    titleKey: "provider.company.title",
    featured: "provider.company.featured",
    priceKey: "provider.company.price",
    featuresKeys: [
      "provider.company.features.0",
      "provider.company.features.1",
      "provider.company.features.2",
      "provider.company.features.3",
      "provider.company.features.4",
      "provider.company.features.5",
    ],
    ctaKey: "provider.company.cta",
    currency: "provider.company.currency",
    period: "provider.company.period",
  },
]

export const PlanListForPatient = [
  {
    type: PlanTypeForPatient.Individual,
    titleKey: "patient.individual.title",
    priceKey: "patient.individual.price",
    featuresKeys: [
      "patient.individual.features.0",
      "patient.individual.features.1",
      "patient.individual.features.2",
      "patient.individual.features.3",
      "patient.individual.features.4",
    ],
    ctaKey: "patient.individual.cta",
  },
  {
    type: PlanTypeForPatient.Patient,
    titleKey: "patient.patient.title",
    priceKey: "patient.patient.price",
    featuresKeys: [
      "patient.patient.features.0",
      "patient.patient.features.1",
      "patient.patient.features.2",
      "patient.patient.features.3",
      "freeServices",
      "patient.patient.features.4",
      "patient.patient.features.5",
      "patient.patient.features.6",
      "patient.patient.features.7",
      "patient.patient.features.8",
    ],
    ctaKey: "patient.patient.cta",
    currency: "patient.patient.currency",
    period: "patient.patient.period",
  },
  {
    type: PlanTypeForPatient.Family,
    titleKey: "patient.family.title",
    priceKey: "patient.family.price",
    featuresKeys: [
      "patient.family.features.0",
      "patient.family.features.1",
      "patient.family.features.2",
      "patient.family.features.3",
    ],
    ctaKey: "patient.family.cta",
    currency: "patient.family.currency",
    period: "patient.family.period",
  },
]
